In [1]:
from  __future__ import print_function
import torch as t

In [3]:
a = t.randn(3,4,requires_grad = True)
a

tensor([[-0.0843,  1.6496, -0.1669,  0.5493],
        [-1.5608, -0.0453,  2.4357,  0.2854],
        [ 0.3648, -0.2969,  0.2154, -0.0692]], requires_grad=True)

In [4]:
b = t.ones(3,4).requires_grad_()
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

In [5]:
c = a.add(b)
c

tensor([[ 0.9157,  2.6496,  0.8331,  1.5493],
        [-0.5608,  0.9547,  3.4357,  1.2854],
        [ 1.3648,  0.7031,  1.2154,  0.9308]], grad_fn=<AddBackward0>)

In [8]:
a.requires_grad

True

In [9]:
a.is_leaf, b.is_leaf, c.is_leaf

(True, True, False)

In [10]:
c.grad is None

True

In [11]:
a.grad is None

True

In [15]:
def f(x):
    y = 2*x**2
    return y
def gradf(x):
    dx = 4*x
    return dx

In [18]:
x = t. ones(3,4,requires_grad = True)
y = f(x)
dx = gradf(x)
dx

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]], grad_fn=<MulBackward0>)

In [17]:
y.backward(t.ones(y.size()))
x.grad

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])