In [2]:
import numpy as np
import torch

In [11]:
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],
                   [69,96,70]],dtype = 'float32')
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],
                  dtype = 'float32')

In [18]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(target)

In [12]:
w = torch.randn(2,3,requires_grad = True)
b = torch.randn(2,requires_grad = True)

In [13]:
def model(x):
    return x@w.t() + b

In [19]:
preds = model(inputs)
print(preds)

tensor([[ -60.3357,   -9.5570],
        [ -73.2857,  -20.2974],
        [-111.3345,  -73.7624],
        [ -56.9628,   51.1176],
        [ -66.9585,  -55.4808]], grad_fn=<AddBackward0>)


In [16]:
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [21]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [22]:
loss = mse(preds,targets)
print(loss)

tensor(21994.8965, grad_fn=<DivBackward0>)


In [23]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-12470.5898, -14389.5742,  -8610.9678],
        [ -9086.6445, -11970.7490,  -6973.5010]])
tensor([-149.9754, -113.5960])


In [24]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

##### preds = model(inputs)
loss = mse(preds,targets)
print(loss)

In [27]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(15516.8672, grad_fn=<DivBackward0>)


In [28]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [29]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(634.7553, grad_fn=<DivBackward0>)


In [30]:
preds

tensor([[ 61.3594,  80.6905],
        [ 88.4467, 103.6683],
        [ 97.7611, 109.4479],
        [ 45.1272,  97.6235],
        [ 98.8804,  88.8481]], grad_fn=<AddBackward0>)