In [16]:
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
import torch.nn.functional as F

In [17]:
inputs = np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],
                   [69,96,70]],dtype = 'float32')
targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],
                  dtype = 'float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [18]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [25]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle = True)

In [19]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1982,  0.0568, -0.3084],
        [-0.1065,  0.5249,  0.2444]], requires_grad=True)
Parameter containing:
tensor([-0.4262, -0.4609], requires_grad=True)


In [20]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1982,  0.0568, -0.3084],
         [-0.1065,  0.5249,  0.2444]], requires_grad=True),
 Parameter containing:
 tensor([-0.4262, -0.4609], requires_grad=True)]

In [21]:
preds = model(inputs)
preds

tensor([[ 4.5836, 37.4439],
        [ 2.8668, 51.6831],
        [ 6.5379, 74.7876],
        [10.8170, 20.2914],
        [-2.8885, 59.6919]], grad_fn=<AddmmBackward>)

In [22]:
loss_fn = F.mse_loss
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(4341.0952, grad_fn=<MseLossBackward>)


In [23]:
opt = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [33]:
def fit(num_epochs,model,loss_fn,opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if(epoch+1)%200 == 0:
            print('Epoch[{}/{}],loss:{:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [34]:
fit(2000,model,loss_fn ,opt)

Epoch[200/2000],loss:0.5877
Epoch[400/2000],loss:0.5610
Epoch[600/2000],loss:0.5425
Epoch[800/2000],loss:0.5298
Epoch[1000/2000],loss:0.5211
Epoch[1200/2000],loss:0.5151
Epoch[1400/2000],loss:0.5110
Epoch[1600/2000],loss:0.5081
Epoch[1800/2000],loss:0.5062
Epoch[2000/2000],loss:0.5048


In [35]:
preds = model(inputs)
preds

tensor([[ 57.0991,  70.2360],
        [ 82.2079, 100.6863],
        [118.7957, 133.0377],
        [ 21.1160,  37.0436],
        [101.8181, 119.0589]], grad_fn=<AddmmBackward>)

In [29]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])